version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: Hotel_Booking_Container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: t7)rpjDB
      POSTGRES_DB: Hotel_Booking_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: